# -*- coding: utf-8 -*-
"""Aula 130.B Avaliação, Ajuste e Seleção de Modelos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ocQAB6HEjQNIIDs7f-Hvl0fzrTfOe_Y

Considerando a matriz de confusão a seguir (Tabela com a convenção de que
as linhas representam a classe real e as colunas a classe predita), calcule:
"""

from IPython.display import HTML, display

# Define the HTML code for your table as a string
html_table_string = """<table border=1><thead><tr><th colspan=3>Matriz de confusão para um problema com duas classes</th></tr></thead><tbody><tr align='center'><td></td><td >+</td><td>-</td></tr><tr align='center'><td>+</td><td>100</td><td>50</td></tr><tr align='center'><td>-</td><td>30</td><td>120</td></tr></tbody></table>"""

# Display the HTML string as a rendered table
display(HTML(html_table_string))

# Valores da tabela
TP = 100
FN = 50
FP = 30
TN = 120

# @title Neste parágrafo, calcule a Acurácia

total = TP + TN + FP + FN
acuracia = (TP + TN) / total

print(f"Acurácia: {acuracia:.2f}")

# @title Neste parágrafo, calcule a Precisão

precisao = TP / (TP + FP)

print(f"Precisão: {precisao:.2f}")

# @title Neste parágrafo, calcule a Revocação

revocacao = TP / (TP + FN)

print(f"Revocação: {revocacao:.2f}")

# @title Neste parágrafo, calcule a Medida F1-score

f1_score = 2 * (precisao * revocacao) / (precisao + revocacao)

print(f"F1-Score: {f1_score:.2f}")

# @title Neste parágrafo, calcule a Medida Especificidade

especificidade = TN / (TN + FP)

print(f"Especificidade: {especificidade:.2f}")