# -*- coding: utf-8 -*-
"""Aula 060. Estatística para Exploração de dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MgUxYBiLSymOk18Kh9dTd4nCyXNNYsk4

# Instalação de bibliotecas
"""

# Realize a instalação de bibliotecas neste parágrafo

!pip install numpy
!pip install pandas
!pip install matplotlib
!pip install seaborn

"""# Importação de bibliotecas"""

# Realize a importação de bibliotecas neste parágrafo

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# Leitura do arquivo

Utilize os dados disponíveis no repositório [Student Performance](https://archive.ics.uci.edu/dataset/320/student+performance) do UCI.
"""

# Leia o arquivo neste parágrafo

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab Notebooks/student-mat.csv'

df = pd.read_csv(file_path, sep=';')

"""# Análise Univariada

Para os cálculos da **análise univariada** utilize a coluna `age`

## Medidas de Frequência

### Frequência absoluta
"""

# Realize o cálculo neste parágrafo

freq_absoluta = df['age'].value_counts().sort_index()
print(freq_absoluta)

"""### Frequência relativa"""

# Realize o cálculo neste parágrafo

freq_relativa = freq_absoluta / freq_absoluta.sum()
print(freq_relativa)

"""### Frequência absoluta acumulada"""

# Realize o cálculo neste parágrafo

freq_absoluta_acumulada = freq_absoluta.cumsum()
print(freq_absoluta_acumulada)

"""### Frequência relativa absoluta acumulada"""

# Realize o cálculo neste parágrafo

freq_relativa_acumulada = freq_relativa.cumsum()
print(freq_relativa_acumulada)

"""## Medidas de localidade

### Mediana
"""

# Realize o cálculo neste parágrafo

mediana = df['age'].median()
print(mediana)

"""### 1º Quartil"""

# Realize o cálculo neste parágrafo

q1 = df['age'].quantile(0.25)
print(q1)

"""### 3º Quartil"""

# Realize o cálculo neste parágrafo

q3 = df['age'].quantile(0.75)
print(q3)

"""### Moda"""

# Realize o cálculo neste parágrafo

moda = df['age'].mode()
print(moda)

"""## Medidas de espalhamento

### Amplitude
"""

# Realize o cálculo neste parágrafo

amplitude = df['age'].max() - df['age'].min()
print(amplitude)

"""### Distância entre o 3º e o 1º quartil"""

# Realize o cálculo neste parágrafo

iqr = q3 - q1
print(iqr)

"""### Desvio médio absoluto"""

# Realize o cálculo neste parágrafo

desvio_medio_absoluto = df['age'].sub(df['age'].mean()).abs().mean()
print(desvio_medio_absoluto)

"""### Variância"""

# Realize o cálculo neste parágrafo

variancia = df['age'].var()
print(variancia)

"""### Desvio-padrão"""

# Realize o cálculo neste parágrafo

desvio_padrao = df['age'].std()
print(desvio_padrao)

"""## Medidas de distribuição

### Obliquidade
"""

# Realize o cálculo neste parágrafo

obliquidade = df['age'].skew()
print(obliquidade)

"""Explique o resultado neste parágrafo:

Por se tratar de um resultado maior do que 0 (obliquidade positiva), a distribuição de idades se concentra mais do lado esquerdo.

### Curtose
"""

# Realize o cálculo neste parágrafo

curtose = df['age'].kurtosis()
print(curtose)

"""Explique o resultado neste parágrafo:

Por se tratar de um resultado menor do que zero (curtose negativa), o histograma de distribuição de dados apresenta uma distribuição mais achatada que a distribuição normal.

# Análise Multivariada

Para os cálculos da análise muiltivariada utilize os campos `studytime` e `failures`.

## Covariância
"""

# Realize o cálculo neste parágrafo

covariancia = df[['studytime', 'failures']].cov()
print(covariancia)

"""Explique o resultado neste parágrafo:

De modo que a covariância é negativa, os atributos são inversamente relacionados, quando um valor aumenta, o outro diminui.

## Correlação linear
"""

# Realize o cálculo neste parágrafo

correlacao_linear = df[['studytime', 'failures']].corr()
print(correlacao_linear)

"""Explique o resultado neste parágrafo:

Por se tratar de um número negativo e próximo de zero, demonstra uma relação inversa e fraca.
"""
