# -*- coding: utf-8 -*-
"""Aula 040 Simbolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tun10l6YSba_swS1ca1_cpfE1TYLuRIT

Escreva a função simbolo() que aceita um arquivo como entrada. O arquivo terá nomes de empresa e símbolos de ações. Nesse arquivo, um nome de empresa ocupará uma linha e seu símbolo de ação estará na linha seguinte. Após essa linha estará uma linha com outro nome de empresa e assim por diante. Seu programa lerá o arquivo e armazenará o nome e o símbolo da ação em um dicionário. Depois, ele fornecerá uma interface para o usuário, de modo que ele possa obter o símbolo da ação para determinada empresa. Teste seu código na lista NASDAQ 100 de ações, dada no arquivo nasdaq.txt.

Implemete o código no Google Colab.

Compartilhe o hiperlink do seu notebook no espaço abaixo.

**Utilizar este arquivo (Carregue e leia a partir do seu Google Drive):** nasdaq.txt

**Exemplo de chamada da função:** *simbolo(doc)*

**Resultado da função:**

Digite o nome da empresa: Yahoo

Símbolo da ação: YHOO

Digite o nome da empresa: Microsoft Corp

Símbolo da ação: MSFT

Digite o nome da empresa: YYY

Empresa não encontrada!

Digite o nome da empresa:

Fim do programa!
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab Notebooks/nasdaq.txt'

def simbolo(arquivo):
  dicionario = {}

  with open(arquivo, 'r') as file:
    linhas = [line.strip() for line in file.readlines()]

    for i in range(0, len(linhas), 2):
            nome = linhas[i]
            if i + 1 < len(linhas):
                simbolo = linhas[i+1]
                dicionario[nome.casefold()] = simbolo

  while True:
          empresa = input("Digite o nome da empresa: ").casefold()
          if empresa == "":
              print("Fim do programa!")
              break
          elif empresa in dicionario:
              print("Símbolo da ação:", dicionario[empresa])
          else:
              print("Empresa não encontrada!")

simbolo(file_path)