# -*- coding: utf-8 -*-
"""Aula 120. Modelagem de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nraSP1CekPPtpublXvDnrO1ii1aTn3B7

# Importação de bibliotecas
"""

from google.colab import drive

import pandas as pd

# Utilizando hold-out como técnica de re-amostragem
from sklearn.model_selection import train_test_split

# Importando o classificador baseado em Árvore de Decisão
from sklearn.tree import DecisionTreeClassifier

# Importando a métrica de acurácia para avaliação das respostas
from sklearn.metrics import accuracy_score

from sklearn.datasets import fetch_california_housing

# Importando o regressor baseado em Árvore de Decisão
from sklearn.tree import DecisionTreeRegressor

# Importando a métrica do erro médio quadrático para avaliação do desempenho
from sklearn.metrics import mean_squared_error

"""# Montar o Google Drive"""

drive.mount('/content/drive', force_remount=True)

"""# Ler o arquivo

Utilizaremos o conjunto de dados de [diabetes](https://drive.google.com/file/d/18ZzX340BybQNiaov8Loy5bo-QamLA7SJ/view?usp=sharing) para a indução de modelos.
"""

file_path = '/content/drive/MyDrive/Colab Notebooks/diabetes.csv'

df = pd.read_csv(file_path);

df

"""# Comitês de Modelos

## Aplicação dos Algoritmos de Modelagem: Python

### Pipeline de Classificação
"""

# @title Neste parágrafo, separe os dados em atributos preditivos (X) e atributo alvo (y)

X = df.drop('Outcome', axis=1)
y = df['Outcome']

# @title Neste parágrafo, imprima apenas os atributos preditivos

X

# @title Neste parágrafo, imprima apenas o atributo alvo

y

# @title Neste parágrafo, aplique a técnica de hold-out com 30% para o teste, semente igual a 12 e mantenha a proporção das classes nas amostras de treinamento e teste.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12, stratify=y)

# @title Neste parágrafo, inicialize o classificador Árvore de decisão (DecisionTreeClassifier), com a semente igual a 42.

clf = DecisionTreeClassifier(random_state=42)

# @title Neste parágrafo, ajuste o modelo aos dados (Treinamento)

clf.fit(X_train, y_train)

# @title Neste parágrafo, submeta o conjunto de dados de teste ao modelo treinado

y_pred = clf.predict(X_test)

# @title Neste parágrafo, mostre a acurácia com base nas respostas esperadas

acc = accuracy_score(y_test, y_pred)
print(f'Acurácia do modelo: {acc:.4f}')

"""### Pipeline de Regressão

Para a tarefa de regressão, utilizaremos o conjunto de dados de preços de residências na [Califórnia](https://www.kaggle.com/datasets/camnugent/california-housing-prices) que pode ser carregado diretamente da biblioteca do scikit-learn.

* Ele possui dados do censo de 1990 com informações sobre a posição geográfica, as características do imóvel e a renda média dos ocupantes.
* A tarefa tem como foco a modelagem do preço final de venda do imóvel. Será induzido um modelo para predizer o valor de venda de um imóvel.
"""

# @title Carregando os dados
califa_dataset = fetch_california_housing()

# @title Mostrando os dados
califa_dataset

# @title Neste parágrafo, separe os atributos preditivos (data) do atributo alvo (target)

X_califa = califa_dataset.data
y_califa = califa_dataset.target

# @title Neste parágrafo, imprima os atributos preditivos (data)

X_califa

# @title Neste parágrafo, imprima o atributo alvo (target)

y_califa

# @title Neste parágrafo, aplique a técnica de hold-out com 20% para o teste e o valor da semente igual a 12

X_train_califa, X_test_califa, y_train_califa, y_test_califa = train_test_split(X_califa, y_califa, test_size=0.2, random_state=12)

# @title Neste parágrafo, inicialize o modelo DecisionTreeRegressor

reg = DecisionTreeRegressor()

# @title Neste parágrafo, treine o modelo

reg.fit(X_train_califa, y_train_califa)

# @title Neste parágrafo, submeta os dados do conjunto de teste ao modelo

y_pred_califa = reg.predict(X_test_califa)

# @title Neste parágrafo, calcule o erro das predições com base no valor esperado

mse = mean_squared_error(y_test_califa, y_pred_califa)
print(f'Erro Médio Quadrático (MSE): {mse:.4f}')