# -*- coding: utf-8 -*-
"""Aula 050. Python para Ciência de Dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0qzkTi59amlS8zMGp28FUIKyegFjm10

# Avaliação contínua

* Utilize os dados do repositório [UCI Student Performance](https://archive.ics.uci.edu/dataset/320/student+performance)
* Copie este *Notebook* para a sua conta no Google
* Atribua acesso de leitura a todos os usuários do IFSP no *Notebook* copiado
* Realize as atividades no parágrafo indicado
* Copie e cole a URL do seu Notebook no formulário da Avaliação contínua
"""

# Conectando ao drive

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/Colab Notebooks/student-mat.csv'

df = pd.read_csv(file_path, sep=';')

"""## Imprima as informações gerais do dataframe"""

# Construa o código

print("Informações Gerais do DataFrame:\n")
df.info()

"""## Imprima a lista com o nome de todas as colunas"""

# Construa o código

print("Lista Com o Nome de Todas as Colunas:\n")
print(df.columns.tolist())

"""## Calcule as medidas estatísticas para cada coluna"""

# Construa o código

print("Cálculo das Medidas Estatísticas de Cada Coluna:\n")
print(df.describe())

"""## Renomeie a coluna `age` para `idade`"""

# Construa o código

df = df.rename(columns={'age': 'idade'})

print("Lista Com o Nome de Todas as Colunas para Verificar Age -> Idade:\n")
print(df.columns.tolist())

"""## Faça uma copia da coluna `idade` para a coluna `idade-copia`"""

# Construa o código

df['idade-copia'] = df['idade']

print("Primeiras Linhas das Colunas para Verificar Idade-Copia:\n")
print(df.head())

"""## Remova a coluna `idade-copia`"""

# Construa o código

df = df.drop(columns=['idade-copia'])

print("Primeiras Linhas das Colunas para Verificar Idade-Copia Removida:\n")
print(df.head())

"""## Mostre as linhas que possuem idade maior que 18 e menor que 21 anos"""

# Construa o código

filtro = df[(df['idade'] > 18) & (df['idade'] < 21)]

print("Linhas com Idade Maior que 18 e Menor que 21:\n")
print(filtro)

"""## Ordene o *dataframe* pelo número de faltas dos alunos (Decrescente)"""

# Construa o código

ordenacao = df.sort_values(by='absences', ascending=False)

print("DataFrame Ordenado pelo Número de Faltas dos Alunos (Decrescente):\n")
print(ordenacao)